<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_user_login_form_alter().
 */
function custom_block_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id){
  $form['#submit'][] = 'custom_block_user_login_form_submit';
}

/**
 * Implements hook_form_user_login_form_submit().
 */
function custom_block_user_login_form_submit($form, FormStateInterface $form_state) {
  $url = Url::fromRoute('custom_block.example');
  $form_state->setRedirectUrl($url);
}
// custom_block.example
