<?php

declare(strict_types=1);

/**
 * @file
 * Provides an awards entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function awards_theme(): array {
  return [
    'awards' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for awards templates.
 *
 * Default template: awards.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the awards information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_awards(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

