<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_cron().
 */
function mymodule_cron() {
  \Drupal::messenger()->addMessage(t('This message will be diplsyed after run cron - Md Nazar Ali'));
}

/**
 * Implements hook_form_alter().
 */
function mymodule_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t('Click here to Save');
  }
}
